CREATE DATABASE DCHAN;
USE DCHAN;

CREATE TABLE BOARD(
    slug VARCHAR(4),
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY(slug)
);

DROP TABLE THREAD;
CREATE TABLE THREAD(
    id BIGINT,
    subject VARCHAR(256) DEFAULT '' NOT NULL,
    author VARCHAR(50) DEFAULT 'Anonymous' NOT NULL,
    comment VARCHAR(512) NOT NULL,
    fileurl VARCHAR(512) DEFAULT NULL,
    published DATETIME DEFAULT CURRENT_TIMESTAMP,
    sticky BOOLEAN DEFAULT FALSE NOT NULL,
    closed BOOLEAN DEFAULT FALSE NOT NULL,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,
    board VARCHAR(4) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (board) REFERENCES BOARD(slug)
);

DROP TABLE POST;
CREATE TABLE POST(
    id BIGINT,
    author VARCHAR(50) DEFAULT 'Anonymous' NOT NULL,
    comment VARCHAR(512) NOT NULL,
    fileurl VARCHAR(512) DEFAULT NULL,
    published DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE NOT NULL,
    thread BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (thread) REFERENCES THREAD(id)
);